version: '3.4'
services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timescale-postgis-test
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data